"""

Revision ID: 079dd315e4c3
Revises: 0004_therapeutic
Create Date: 2026-04-05 02:45:38.222774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079dd315e4c3'
down_revision: Union[str, None] = '0004_therapeutic'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_embedding_chunks_conversation_id'), table_name='embedding_chunks')
    op.drop_index(op.f('ix_embedding_chunks_embedding_cosine'), table_name='embedding_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_embedding_chunks_embedding_cosine'), 'embedding_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_embedding_chunks_conversation_id'), 'embedding_chunks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
